# info CRUD routes

@url = http://localhost:3000/api/infos

@id = 67

### Get All infos
GET {{url}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Get One info by ID
GET {{url}}/{{id}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Create info
POST {{url}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "label": "RGOCC Fiche 1", 
  "description": "desc de la fiche info",
  "content": "abcdef",
  "teamId": "1",
  "userId": "1"
}

### Update info by ID
PATCH {{url}}/{{id}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "label": "test"
}

### Delete info by ID
DELETE {{url}}/{{id}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
