export const validationMessages = {
  label: "Le titre est obligatoire",
  description: "La description est obligatoire",
  content: "Le contenu est obligatoire",
  expirationDate: "La date n'est pas valide",
  userId: "L'utilisateur est obligatoire",
  teamId: "L'équipe est obligatoire",
  letterHead: "L'entête de l'équipe est obligatoire",
  emailInvalid: "Email invalide",
  emailRequired: "L'email est requis",
  phoneInvalid: "Numéro invalide",
  phoneRequired: "Le téléphone est requis",
  lattitudeInvalid: "La lattitude doit être un nombre entre -90 et 90",
  longitudeInvalid: "La longitude doit être un nombre entre -180 et 180",
  altitudeInvalid: "L'altitude doit être un nombre",
  streetTooLong: "L'adresse ne doit pas dépasser 255 caractères",
  cityTooLong: "Le nom de la ville ne doit pas dépasser 100 caractères",
  postalCodeInvalid: "Le code postal doit contenir 5 chiffres",
  countryTooLong: "Le nom du pays ne doit pas dépasser 100 caractères",
};
